"""Core tables: users, identities, admin audit, config meta, attention items.

Stage 0 keeps ``users`` minimal; later stages add columns through Alembic migrations
(stage 2: ``wallet_minor``).
"""

from __future__ import annotations

import sqlalchemy as sa

from svbg.db.meta import JSONB, UtcDateTime, metadata, now_default

__all__ = [
    "ATTENTION_SEVERITIES",
    "USER_ROLES",
    "admin_audit",
    "attention_items",
    "config_meta",
    "staff_roles",
    "user_identities",
    "users",
]

USER_ROLES: tuple[str, ...] = ("user", "support", "admin", "owner")
ATTENTION_SEVERITIES: tuple[str, ...] = ("info", "warn", "error")


def _in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({quoted})"


# UUIDv7 generated by PostgreSQL itself (PG 13+, no extension): a random v4 UUID whose first 48 bits are
# replaced with the Unix time in ms and whose version nibble is switched 4 -> 7. Same text form as
# ``svbg.core.ids.uuid7()``: application code may pass its own value, raw inserts still get a valid id.
_UUID7_SQL = (
    "(encode(set_bit(set_bit(overlay(uuid_send(gen_random_uuid()) placing "
    "substring(int8send(floor(extract(epoch from clock_timestamp()) * 1000)::bigint) from 3) "
    "from 1 for 6), 52, 1), 53, 1), 'hex')::uuid)::text"
)

users = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
    sa.Column("telegram_id", sa.BigInteger, nullable=True, unique=True),
    sa.Column("public_id", sa.Text, nullable=False, unique=True, server_default=sa.text(_UUID7_SQL)),
    sa.Column("username", sa.Text, nullable=True),
    sa.Column("first_name", sa.Text, nullable=True),
    sa.Column("language", sa.Text, nullable=True),
    sa.Column("role", sa.Text, nullable=False, server_default=sa.text("'user'")),
    sa.Column("perms", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
    sa.Column("created_at", UtcDateTime, nullable=False, server_default=now_default()),
    sa.Column("last_seen_at", UtcDateTime, nullable=True),
    sa.Column("bot_blocked_at", UtcDateTime, nullable=True),
    sa.Column("banned_at", UtcDateTime, nullable=True),
    # Stage 2 wallet (07 §4.5): the balance in minor units of the shop currency; every change is a row of
    # ``wallet_ledger`` (svbg.billing) written in the same transaction — Σ ledger = wallet_minor.
    sa.Column("wallet_minor", sa.BigInteger, nullable=False, server_default=sa.text("0")),
    # Stage 3: «акции и новости» opt-in of marketing broadcasts (``svbg.broadcasts.segments``).
    sa.Column("notify_marketing", sa.Boolean, nullable=False, server_default=sa.true()),
    # Entry captcha (``svbg.tg.user.captcha``): when the user tapped the right emoji; NULL — not passed yet.
    # Users who were there before the captcha (migration 0006) and imported users are marked passed.
    sa.Column("captcha_passed_at", UtcDateTime, nullable=True),
    # Custom staff role (``svbg.services.staff_roles``, migration 0007): the member has exactly its rights,
    # copied into ``perms``; ``role`` is the rank they need. NULL — a plain user, an owner or classic staff.
    sa.Column(
        "staff_role_id",
        sa.BigInteger,
        sa.ForeignKey("staff_roles.id", ondelete="SET NULL"),
        nullable=True,
    ),
    sa.CheckConstraint(_in("role", USER_ROLES), name="role"),
    sa.CheckConstraint("wallet_minor >= 0", name="wallet_minor"),
    sa.CheckConstraint("jsonb_typeof(perms) = 'array'", name="perms_array"),
    # Staff list (support/admin/owner) is tiny; a partial index keeps role checks cheap.
    sa.Index("ix_users_staff_role", "role", postgresql_where=sa.text("role <> 'user'")),
    sa.Index(
        "ix_users_staff_role_id", "staff_role_id", postgresql_where=sa.text("staff_role_id IS NOT NULL")
    ),
)

#: Custom staff roles: a name and a set of rights (``svbg.services.staff_roles``). Members point here with
#: ``users.staff_role_id``; deleting a role leaves its members without one.
staff_roles = sa.Table(
    "staff_roles",
    metadata,
    sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
    sa.Column("name", sa.Text, nullable=False, unique=True),
    sa.Column("perms", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
    sa.Column("created_at", UtcDateTime, nullable=False, server_default=now_default()),
    sa.Column("updated_at", UtcDateTime, nullable=False, server_default=now_default()),
    sa.CheckConstraint("length(btrim(name)) BETWEEN 1 AND 40", name="name"),
    sa.CheckConstraint("jsonb_typeof(perms) = 'array'", name="perms_array"),
)

user_identities = sa.Table(
    "user_identities",
    metadata,
    sa.Column(
        "user_id",
        sa.BigInteger,
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column("provider", sa.Text, nullable=False),
    sa.Column("subject", sa.Text, nullable=False),
    sa.Column("verified_at", UtcDateTime, nullable=True),
    sa.PrimaryKeyConstraint("provider", "subject", name="pk_user_identities"),
    sa.CheckConstraint("length(provider) > 0 AND length(subject) > 0", name="not_empty"),
    sa.Index("ix_user_identities_user_id", "user_id"),
)

admin_audit = sa.Table(
    "admin_audit",
    metadata,
    sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
    sa.Column("ts", UtcDateTime, nullable=False, server_default=now_default()),
    sa.Column("actor_id", sa.BigInteger, nullable=True),  # NULL = system / CLI on the host
    sa.Column("role", sa.Text, nullable=True),
    sa.Column("action", sa.Text, nullable=False),
    sa.Column("target", sa.Text, nullable=True),
    sa.Column("amount_minor", sa.BigInteger, nullable=True),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column("batch_id", sa.Text, nullable=True),
    sa.Column("details", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    # 04 §9.1: every money action must carry a reason.
    sa.CheckConstraint(
        "amount_minor IS NULL OR (reason IS NOT NULL AND length(btrim(reason)) > 0)",
        name="money_reason",
    ),
    sa.CheckConstraint("length(action) > 0", name="action_not_empty"),
    sa.Index("ix_admin_audit_ts", "ts"),
    sa.Index("ix_admin_audit_actor_ts", "actor_id", "ts"),
    sa.Index("ix_admin_audit_target", "target", postgresql_where=sa.text("target IS NOT NULL")),
    sa.Index("ix_admin_audit_batch", "batch_id", postgresql_where=sa.text("batch_id IS NOT NULL")),
)

config_meta = sa.Table(
    "config_meta",
    metadata,
    sa.Column("key", sa.Text, primary_key=True),
    sa.Column("value", JSONB, nullable=True),
    sa.Column("updated_at", UtcDateTime, nullable=False, server_default=now_default()),
)

attention_items = sa.Table(
    "attention_items",
    metadata,
    sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
    sa.Column("dedup_key", sa.Text, nullable=False, unique=True),
    sa.Column("severity", sa.Text, nullable=False),
    sa.Column("title", sa.Text, nullable=False),
    sa.Column("body", sa.Text, nullable=False, server_default=sa.text("''")),
    sa.Column("fix_action", sa.Text, nullable=True),
    sa.Column("created_at", UtcDateTime, nullable=False, server_default=now_default()),
    sa.Column("updated_at", UtcDateTime, nullable=False, server_default=now_default()),
    sa.Column("snoozed_until", UtcDateTime, nullable=True),
    sa.Column("resolved_at", UtcDateTime, nullable=True),
    sa.CheckConstraint(_in("severity", ATTENTION_SEVERITIES), name="severity"),
    sa.CheckConstraint("length(dedup_key) > 0", name="dedup_key_not_empty"),
    # Open items are few and read on every admin home screen.
    sa.Index(
        "ix_attention_items_open",
        "updated_at",
        postgresql_where=sa.text("resolved_at IS NULL"),
    ),
)
