"""Stage 1: Remnawave sync, subscriptions, admin chat.

Tables: ``subscriptions``, ``subscription_events``, ``panel_squad_substitutions``, ``panel_squad_twins``
(``svbg.subscriptions.tables``); ``rw_inbox``, ``import_runs``, ``rw_sync_state`` (``svbg.remnawave.tables``);
``admin_topics``, ``admin_cards`` (``svbg.services.tables``).

Generated by ``alembic revision --autogenerate`` against a database at ``0001_initial`` (PostgreSQL 17), then
reviewed by hand: the autogenerate false positive on ``users.public_id`` (same default expression, different
text after PostgreSQL normalised it) was removed. ``tests/e2e/test_migrations.py`` checks that
``upgrade head`` produces exactly the schema of ``svbg.db.schema.create_schema``.

Revision ID: 0002_stage1
Revises: 0001_initial
Create Date: 2026-10-01
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_stage1"
down_revision: str | None = "0001_initial"
branch_labels: str | None = None
depends_on: str | None = None

# UUIDv7 computed by PostgreSQL (same expression as ``svbg.subscriptions.tables``; frozen here on purpose).
_UUID7_SQL = (
    "(encode(set_bit(set_bit(overlay(uuid_send(gen_random_uuid()) placing "
    "substring(int8send(floor(extract(epoch from clock_timestamp()) * 1000)::bigint) from 3) "
    "from 1 for 6), 52, 1), 53, 1), 'hex')::uuid)::text"
)


def upgrade() -> None:
    op.create_table(
        "admin_cards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("msg_id", sa.BigInteger(), nullable=True),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(state) = 'object'", name=op.f("ck_admin_cards_state_object")),
        sa.CheckConstraint(
            "length(kind) > 0 AND length(ref) BETWEEN 1 AND 200", name=op.f("ck_admin_cards_ref_len")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_cards")),
        sa.UniqueConstraint("kind", "ref", name="uq_admin_cards_kind_ref"),
    )
    op.create_table(
        "admin_topics",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("icon_emoji_id", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("fallback", sa.Text(), server_default=sa.text("'system'"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("recreated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("fallback IN ('system', 'drop')", name=op.f("ck_admin_topics_fallback")),
        sa.CheckConstraint("length(kind) BETWEEN 1 AND 32", name=op.f("ck_admin_topics_kind_len")),
        sa.CheckConstraint(
            "thread_id IS NULL OR chat_id IS NOT NULL", name=op.f("ck_admin_topics_thread_has_chat")
        ),
        sa.PrimaryKeyConstraint("kind", name=op.f("pk_admin_topics")),
    )
    op.create_table(
        "import_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'running'"), nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column(
            "report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('dry_run', 'apply')", name=op.f("ck_import_runs_mode")),
        sa.CheckConstraint("status IN ('running', 'done', 'failed')", name=op.f("ck_import_runs_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_runs")),
    )
    op.create_index("ix_import_runs_source_started", "import_runs", ["source", "started_at"], unique=False)
    op.create_table(
        "panel_squad_twins",
        sa.Column("substitute_squad_uuid", sa.Text(), nullable=False),
        sa.Column("base_squad_uuid", sa.Text(), nullable=False),
        sa.Column("owner_module", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "base_squad_uuid <> substitute_squad_uuid", name=op.f("ck_panel_squad_twins_not_identity")
        ),
        sa.PrimaryKeyConstraint("substitute_squad_uuid", name=op.f("pk_panel_squad_twins")),
    )
    op.create_table(
        "rw_inbox",
        sa.Column("hash", sa.Text(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("panel_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "slim",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'new'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('new', 'done', 'skipped', 'error')", name=op.f("ck_rw_inbox_status")),
        sa.CheckConstraint("length(hash) = 64", name=op.f("ck_rw_inbox_hash_len")),
        sa.PrimaryKeyConstraint("hash", name=op.f("pk_rw_inbox")),
    )
    op.create_index(
        "ix_rw_inbox_new_ts", "rw_inbox", ["ts"], unique=False, postgresql_where=sa.text("status = 'new'")
    )
    op.create_index("ix_rw_inbox_received_at", "rw_inbox", ["received_at"], unique=False)
    op.create_table(
        "rw_sync_state",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("holder", sa.Text(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sub_domain", sa.Text(), nullable=True),
        sa.Column(
            "report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_rw_sync_state")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.Text(), server_default=sa.text(_UUID7_SQL), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("plan_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "plan_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("link_state", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("panel_user_id", sa.BigInteger(), nullable=True),
        sa.Column("panel_short_uuid", sa.Text(), nullable=True),
        sa.Column("panel_username", sa.Text(), nullable=True),
        sa.Column("subscription_url", sa.Text(), nullable=True),
        sa.Column("paid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("desired_expire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("desired_traffic_bytes", sa.BigInteger(), nullable=True),
        sa.Column("desired_reset_strategy", sa.Text(), nullable=True),
        sa.Column("desired_device_limit", sa.Integer(), nullable=True),
        sa.Column(
            "desired_squads",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("desired_ext_squad", sa.Text(), nullable=True),
        sa.Column("desired_tag", sa.Text(), nullable=True),
        sa.Column("desired_status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("panel_status", sa.Text(), nullable=True),
        sa.Column("panel_expire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("panel_traffic_limit", sa.BigInteger(), nullable=True),
        sa.Column("panel_used_traffic", sa.BigInteger(), nullable=True),
        sa.Column("panel_reset_strategy", sa.Text(), nullable=True),
        sa.Column("panel_device_limit", sa.Integer(), nullable=True),
        sa.Column("panel_squads", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("panel_ext_squad", sa.Text(), nullable=True),
        sa.Column("panel_tag", sa.Text(), nullable=True),
        sa.Column("panel_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("panel_online_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("panel_first_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("panel_sub_last_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("panel_last_traffic_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("panel_state_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("hold_kind", sa.Text(), nullable=True),
        sa.Column("hold_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hold_frozen_seconds", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "desired_status IN ('active', 'disabled')", name=op.f("ck_subscriptions_desired_status")
        ),
        sa.CheckConstraint(
            "disabled_reason IS NULL OR "
            "disabled_reason IN ('BOT_BAN', 'admin', 'ip_guard', 'channel_left', 'closed')",
            name=op.f("ck_subscriptions_disabled_reason"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(desired_squads) = 'array'", name=op.f("ck_subscriptions_desired_squads_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(overrides) = 'object'", name=op.f("ck_subscriptions_overrides_object")
        ),
        sa.CheckConstraint(
            "link_state <> 'linked' OR panel_user_id IS NOT NULL",
            name=op.f("ck_subscriptions_linked_has_panel_user_id"),
        ),
        sa.CheckConstraint(
            "link_state IN ('pending', 'linked', 'panel_missing', 'closed')",
            name=op.f("ck_subscriptions_link_state"),
        ),
        sa.CheckConstraint(
            "desired_device_limit IS NULL OR desired_device_limit >= 0",
            name=op.f("ck_subscriptions_desired_device_limit"),
        ),
        sa.CheckConstraint(
            "desired_traffic_bytes IS NULL OR desired_traffic_bytes >= 0",
            name=op.f("ck_subscriptions_desired_traffic_bytes"),
        ),
        sa.CheckConstraint(
            "panel_user_id IS NULL OR panel_user_id > 0", name=op.f("ck_subscriptions_panel_user_id_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("panel_short_uuid", name=op.f("uq_subscriptions_panel_short_uuid")),
        sa.UniqueConstraint("panel_user_id", name=op.f("uq_subscriptions_panel_user_id")),
        sa.UniqueConstraint("panel_username", name=op.f("uq_subscriptions_panel_username")),
        sa.UniqueConstraint("public_id", name=op.f("uq_subscriptions_public_id")),
    )
    op.create_index(
        "ix_subscriptions_linked_id",
        "subscriptions",
        ["id"],
        unique=False,
        postgresql_where=sa.text("link_state = 'linked'"),
    )
    op.create_index(
        "ix_subscriptions_panel_expire_at",
        "subscriptions",
        ["panel_expire_at"],
        unique=False,
        postgresql_where=sa.text("link_state = 'linked'"),
    )
    op.create_index(
        "ix_subscriptions_user_id",
        "subscriptions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "panel_squad_substitutions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("base_squad_uuid", sa.Text(), nullable=False),
        sa.Column("substitute_squad_uuid", sa.Text(), nullable=False),
        sa.Column("owner_module", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "base_squad_uuid <> substitute_squad_uuid", name=op.f("ck_panel_squad_substitutions_not_identity")
        ),
        sa.CheckConstraint(
            "length(owner_module) > 0", name=op.f("ck_panel_squad_substitutions_owner_module_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_panel_squad_substitutions_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_panel_squad_substitutions")),
        sa.UniqueConstraint(
            "subscription_id", "base_squad_uuid", name="uq_panel_squad_substitutions_sub_base"
        ),
    )
    op.create_index(
        "ix_panel_squad_substitutions_owner", "panel_squad_substitutions", ["owner_module"], unique=False
    )
    op.create_table(
        "subscription_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("delta_seconds", sa.BigInteger(), nullable=True),
        sa.Column("old_expire", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_expire", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ref_type", sa.Text(), nullable=True),
        sa.Column("ref_id", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(kind) > 0", name=op.f("ck_subscription_events_kind_not_empty")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_events_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_events")),
    )
    op.create_index(
        "ix_subscription_events_sub_ts", "subscription_events", ["subscription_id", "ts"], unique=False
    )
    op.create_index(
        "uq_subscription_events_ref",
        "subscription_events",
        ["subscription_id", "kind", "ref_type", "ref_id"],
        unique=True,
        postgresql_where=sa.text("ref_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "uq_subscription_events_ref",
        table_name="subscription_events",
        postgresql_where=sa.text("ref_id IS NOT NULL"),
    )
    op.drop_index("ix_subscription_events_sub_ts", table_name="subscription_events")
    op.drop_table("subscription_events")
    op.drop_index("ix_panel_squad_substitutions_owner", table_name="panel_squad_substitutions")
    op.drop_table("panel_squad_substitutions")
    op.drop_index(
        "ix_subscriptions_user_id",
        table_name="subscriptions",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_subscriptions_panel_expire_at",
        table_name="subscriptions",
        postgresql_where=sa.text("link_state = 'linked'"),
    )
    op.drop_index(
        "ix_subscriptions_linked_id",
        table_name="subscriptions",
        postgresql_where=sa.text("link_state = 'linked'"),
    )
    op.drop_table("subscriptions")
    op.drop_table("rw_sync_state")
    op.drop_index("ix_rw_inbox_received_at", table_name="rw_inbox")
    op.drop_index("ix_rw_inbox_new_ts", table_name="rw_inbox", postgresql_where=sa.text("status = 'new'"))
    op.drop_table("rw_inbox")
    op.drop_table("panel_squad_twins")
    op.drop_index("ix_import_runs_source_started", table_name="import_runs")
    op.drop_table("import_runs")
    op.drop_table("admin_topics")
    op.drop_table("admin_cards")
