"""Stage 2: catalog, wallet and orders, payment core, trial and required channel, user path.

Tables: ``plans``, ``plan_prices``, ``locations`` (``svbg.catalog.tables``); ``orders``, ``order_items``,
``wallet_ledger``, ``manual_receipts`` (``svbg.billing.tables``); ``payment_instances``, ``payments``,
``payment_events`` (``svbg.payments.tables``); ``trial_grants``, ``channel_members`` and new columns of
``subscriptions`` (``svbg.subscriptions.tables``); ``notification_log`` (``svbg.services.notify_user``);
``user_devices`` (``svbg.tg.user.tables``); ``users.wallet_minor`` (``svbg.core.tables``).

Generated by ``alembic revision --autogenerate`` against a database at ``0002_stage1`` (PostgreSQL 17), then
reviewed by hand: the false positives on ``users.public_id`` / ``subscriptions.public_id`` (same default,
different text after PostgreSQL normalised it) were removed, and the CHECK constraints autogenerate does not
see were added (``subscriptions``: new reasons and the freeze/addon checks; ``users``: the wallet is never
negative). ``tests/e2e/test_migrations.py`` checks that ``upgrade head`` produces exactly the schema of
``svbg.db.schema.create_schema``.

Revision ID: 0003_stage2
Revises: 0002_stage1
Create Date: 2026-10-02
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_stage2"
down_revision: str | None = "0002_stage1"
branch_labels: str | None = None
depends_on: str | None = None

# UUIDv7 computed by PostgreSQL (same expression as ``svbg.core.tables``; frozen here on purpose).
_UUID7_SQL = (
    "(encode(set_bit(set_bit(overlay(uuid_send(gen_random_uuid()) placing "
    "substring(int8send(floor(extract(epoch from clock_timestamp()) * 1000)::bigint) from 3) "
    "from 1 for 6), 52, 1), 53, 1), 'hex')::uuid)::text"
)
_REASONS_OLD = (
    "disabled_reason IS NULL OR disabled_reason IN ('BOT_BAN', 'admin', 'ip_guard', 'channel_left', 'closed')"
)
_REASONS_NEW = (
    "disabled_reason IS NULL OR "
    "disabled_reason IN ('BOT_BAN', 'admin', 'ip_guard', 'channel_left', 'closed', 'hold')"
)
#: CHECK constraints of ``subscriptions`` added in stage 2 (autogenerate does not compare CHECKs).
_SUB_CHECKS: tuple[tuple[str, str], ...] = (
    ("cooldowns_object", "jsonb_typeof(cooldowns) = 'object'"),
    ("hold_kind", "hold_kind IS NULL OR hold_kind IN ('ip_guard', 'admin')"),
    ("hold_has_since", "hold_kind IS NULL OR hold_since IS NOT NULL"),
    ("hold_frozen_seconds", "hold_frozen_seconds >= 0"),
    ("extra_devices", "extra_devices >= 0"),
)


def upgrade() -> None:
    op.create_table(
        "channel_members",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_member", sa.Boolean(), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(status) > 0", name=op.f("ck_channel_members_status_not_empty")),
        sa.PrimaryKeyConstraint("chat_id", "telegram_id", name="pk_channel_members"),
    )
    op.create_table(
        "locations",
        sa.Column("squad_uuid", sa.Text(), nullable=False),
        sa.Column(
            "title",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("flag", sa.Text(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("panel_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("members", sa.Integer(), nullable=True),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(title) = 'object'", name=op.f("ck_locations_title_object")),
        sa.CheckConstraint(
            "flag IS NULL OR length(flag) BETWEEN 1 AND 16", name=op.f("ck_locations_flag_len")
        ),
        sa.CheckConstraint("length(squad_uuid) BETWEEN 1 AND 64", name=op.f("ck_locations_squad_uuid_len")),
        sa.PrimaryKeyConstraint("squad_uuid", name=op.f("pk_locations")),
    )
    op.create_table(
        "payment_instances",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_test", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "method_kinds",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "currencies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("min_minor", sa.BigInteger(), nullable=True),
        sa.Column("max_minor", sa.BigInteger(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("webhook_token", sa.Text(), nullable=False),
        sa.Column("proxy_url", sa.Text(), nullable=True),
        sa.Column(
            "kv",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(currencies) = 'array'", name=op.f("ck_payment_instances_currencies_array")
        ),
        sa.CheckConstraint("jsonb_typeof(kv) = 'object'", name=op.f("ck_payment_instances_kv_object")),
        sa.CheckConstraint(
            "jsonb_typeof(method_kinds) = 'array'", name=op.f("ck_payment_instances_method_kinds_array")
        ),
        sa.CheckConstraint("slug ~ '^[a-z][a-z0-9_]{0,31}$'", name=op.f("ck_payment_instances_slug_format")),
        sa.CheckConstraint(
            "length(provider) BETWEEN 1 AND 32", name=op.f("ck_payment_instances_provider_len")
        ),
        sa.CheckConstraint(
            "min_minor IS NULL OR max_minor IS NULL OR min_minor <= max_minor",
            name=op.f("ck_payment_instances_min_le_max"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_instances")),
        sa.UniqueConstraint("slug", name=op.f("uq_payment_instances_slug")),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column(
            "name",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("availability", sa.Text(), server_default=sa.text("'all'"), nullable=False),
        sa.Column("is_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("traffic_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("reset_strategy", sa.Text(), server_default=sa.text("'NO_RESET'"), nullable=False),
        sa.Column("device_limit", sa.Integer(), nullable=True),
        sa.Column(
            "squads",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("ext_squad", sa.Text(), nullable=True),
        sa.Column("panel_tag", sa.Text(), nullable=True),
        sa.Column("traffic_on_renew", sa.Text(), server_default=sa.text("'reset'"), nullable=False),
        sa.Column("devices_on_renew", sa.Text(), server_default=sa.text("'keep'"), nullable=False),
        sa.Column(
            "device_addon",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("broken_reason", sa.Text(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "availability IN ('all', 'new', 'existing', 'link')", name=op.f("ck_plans_availability")
        ),
        sa.CheckConstraint("code ~ '^[a-z0-9][a-z0-9_]{0,31}$'", name=op.f("ck_plans_code_format")),
        sa.CheckConstraint("devices_on_renew IN ('keep', 'reset')", name=op.f("ck_plans_devices_on_renew")),
        sa.CheckConstraint(
            "jsonb_typeof(device_addon) = 'object'", name=op.f("ck_plans_device_addon_object")
        ),
        sa.CheckConstraint("jsonb_typeof(name) = 'object'", name=op.f("ck_plans_name_object")),
        sa.CheckConstraint("jsonb_typeof(squads) = 'array'", name=op.f("ck_plans_squads_array")),
        sa.CheckConstraint(
            "panel_tag IS NULL OR panel_tag ~ '^[A-Z0-9_]{1,16}$'", name=op.f("ck_plans_panel_tag_format")
        ),
        sa.CheckConstraint(
            "reset_strategy IN ('NO_RESET', 'DAY', 'WEEK', 'MONTH', 'MONTH_ROLLING')",
            name=op.f("ck_plans_reset_strategy"),
        ),
        sa.CheckConstraint(
            "traffic_on_renew IN ('reset', 'carry_over', 'keep')", name=op.f("ck_plans_traffic_on_renew")
        ),
        sa.CheckConstraint(
            "NOT enabled OR jsonb_array_length(squads) >= 1", name=op.f("ck_plans_enabled_has_squads")
        ),
        sa.CheckConstraint("device_limit IS NULL OR device_limit >= 0", name=op.f("ck_plans_device_limit")),
        sa.CheckConstraint("traffic_bytes >= 0", name=op.f("ck_plans_traffic_bytes")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_plans_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_index(
        "uq_plans_trial", "plans", ["is_trial"], unique=True, postgresql_where=sa.text("is_trial")
    )
    op.create_table(
        "payment_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instance_id", sa.BigInteger(), nullable=False),
        sa.Column("payment_id", sa.Text(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("body_sha256", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(summary) = 'object'", name=op.f("ck_payment_events_summary_object")),
        sa.CheckConstraint(
            "outcome IN ('applied', 'duplicate', 'ignored', 'verify_queued', 'mismatch', 'unknown_payment', "
            "'stale', 'test_rejected', 'bad_signature', 'malformed')",
            name=op.f("ck_payment_events_outcome"),
        ),
        sa.CheckConstraint("length(body_sha256) = 64", name=op.f("ck_payment_events_body_sha256_len")),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["payment_instances.id"],
            name=op.f("fk_payment_events_instance_id_payment_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
    )
    op.create_index(
        "ix_payment_events_payment",
        "payment_events",
        ["payment_id"],
        unique=False,
        postgresql_where=sa.text("payment_id IS NOT NULL"),
    )
    op.create_index("ix_payment_events_received_at", "payment_events", ["received_at"], unique=False)
    op.create_index(
        "uq_payment_events_body",
        "payment_events",
        ["instance_id", "body_sha256"],
        unique=True,
        postgresql_where=sa.text("accepted"),
    )
    op.create_table(
        "payments",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text(_UUID7_SQL),
            nullable=False,
        ),
        sa.Column("instance_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("merchant_ref", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("paid_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("paid_currency", sa.Text(), nullable=True),
        sa.Column("method_kind", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "checkout",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_test", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_imported", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("confirmed_by", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("poll_plan", sa.Text(), nullable=True),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_step", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("checks_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(checkout) = 'object'", name=op.f("ck_payments_checkout_object")),
        sa.CheckConstraint("jsonb_typeof(metadata) = 'object'", name=op.f("ck_payments_metadata_object")),
        sa.CheckConstraint(
            "poll_plan IS NULL OR poll_plan IN ('domain', 'nodomain')", name=op.f("ck_payments_poll_plan")
        ),
        sa.CheckConstraint("status <> 'paid' OR paid_at IS NOT NULL", name=op.f("ck_payments_paid_has_time")),
        sa.CheckConstraint(
            "status IN ('pending', 'paid', 'expired', 'canceled', 'failed', 'refunded', 'mismatch')",
            name=op.f("ck_payments_status"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_payments_amount_positive")),
        sa.CheckConstraint("check_step >= 0 AND checks_used >= 0", name=op.f("ck_payments_poll_counters")),
        sa.CheckConstraint("length(currency) BETWEEN 3 AND 8", name=op.f("ck_payments_currency_len")),
        sa.CheckConstraint(
            "paid_amount_minor IS NULL OR paid_amount_minor >= 0", name=op.f("ck_payments_paid_amount")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["payment_instances.id"],
            name=op.f("fk_payments_instance_id_payment_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("instance_id", "external_id", name="uq_payments_instance_external"),
    )
    op.create_index(
        "ix_payments_due",
        "payments",
        ["next_check_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending' AND next_check_at IS NOT NULL"),
    )
    op.create_index(
        "ix_payments_order_id",
        "payments",
        ["order_id"],
        unique=False,
        postgresql_where=sa.text("order_id IS NOT NULL"),
    )
    op.create_index("ix_payments_user_created", "payments", ["user_id", "created_at"], unique=False)
    op.create_table(
        "plan_prices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("highlight", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3,5}$'", name=op.f("ck_plan_prices_currency_format")),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_plan_prices_amount_positive")),
        sa.CheckConstraint("days BETWEEN 1 AND 3650", name=op.f("ck_plan_prices_days")),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_plan_prices_plan_id_plans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_prices")),
        sa.UniqueConstraint("plan_id", "days", "currency", name="uq_plan_prices_plan_days_currency"),
    )
    op.create_table(
        "wallet_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ref_type", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount_minor <> 0", name=op.f("ck_wallet_ledger_amount_not_zero")),
        sa.CheckConstraint("balance_after >= 0", name=op.f("ck_wallet_ledger_balance_after")),
        sa.CheckConstraint("length(reason) BETWEEN 1 AND 32", name=op.f("ck_wallet_ledger_reason_len")),
        sa.CheckConstraint(
            "length(ref_type) BETWEEN 1 AND 32 AND length(ref_id) BETWEEN 1 AND 128",
            name=op.f("ck_wallet_ledger_ref_len"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wallet_ledger_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_ledger")),
        sa.UniqueConstraint("user_id", "reason", "ref_type", "ref_id", name="uq_wallet_ledger_ref"),
    )
    op.create_index("ix_wallet_ledger_ref", "wallet_ledger", ["ref_type", "ref_id"], unique=False)
    op.create_index("ix_wallet_ledger_user_id", "wallet_ledger", ["user_id", "id"], unique=False)
    op.create_table(
        "manual_receipts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("payment_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'submitted'"), nullable=False),
        sa.Column("card_ref", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("decided_by", sa.BigInteger(), nullable=True),
        sa.Column("decided_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'rejected' OR length(btrim(coalesce(decision_reason, ''))) > 0",
            name=op.f("ck_manual_receipts_reject_reason"),
        ),
        sa.CheckConstraint(
            "status = 'submitted' OR decided_at IS NOT NULL", name=op.f("ck_manual_receipts_decided_has_time")
        ),
        sa.CheckConstraint(
            "status IN ('submitted', 'confirmed', 'rejected')", name=op.f("ck_manual_receipts_status")
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_manual_receipts_amount")),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_manual_receipts_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_manual_receipts_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_receipts")),
        sa.UniqueConstraint("payment_id", name=op.f("uq_manual_receipts_payment_id")),
    )
    op.create_index(
        "ix_manual_receipts_open",
        "manual_receipts",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'submitted'"),
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("anchor", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'skipped')", name=op.f("ck_notification_log_status")
        ),
        sa.CheckConstraint(
            "length(target) > 0 AND length(kind) > 0 AND length(anchor) > 0",
            name=op.f("ck_notification_log_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_notification_log_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_log_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_log")),
        sa.UniqueConstraint("target", "kind", "anchor", name="uq_notification_log_target_kind_anchor"),
    )
    op.create_index("ix_notification_log_created_at", "notification_log", ["created_at"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id",
            sa.Text(),
            server_default=sa.text(_UUID7_SQL),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("parent_order_id", sa.BigInteger(), nullable=True),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column("plan_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("autocomplete_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ui_ref", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("ui_stage", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(kind = 'topup' AND status IN ('awaiting_payment', 'credited', 'canceled', 'expired')) OR "
            "(kind <> 'topup' AND status IN ('draft', 'awaiting_funds', 'paid', 'fulfilled', 'canceled', "
            "'expired', 'held'))",
            name=op.f("ck_orders_status_of_kind"),
        ),
        sa.CheckConstraint("jsonb_typeof(snapshot) = 'object'", name=op.f("ck_orders_snapshot_object")),
        sa.CheckConstraint(
            "kind IN ('new', 'renew', 'change', 'addon_devices', 'topup')", name=op.f("ck_orders_kind")
        ),
        sa.CheckConstraint(
            "parent_order_id IS NULL OR kind = 'topup'", name=op.f("ck_orders_parent_only_topup")
        ),
        sa.CheckConstraint(
            "status <> 'awaiting_funds' OR autocomplete_until IS NOT NULL",
            name=op.f("ck_orders_waiting_has_window"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'awaiting_funds', 'awaiting_payment', 'paid', 'fulfilled', 'credited', "
            "'canceled', 'expired', 'held')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint(
            "total_minor >= 0 AND (kind <> 'topup' OR total_minor > 0)", name=op.f("ck_orders_total")
        ),
        sa.CheckConstraint(
            "ui_ref IS NULL OR jsonb_typeof(ui_ref) = 'object'", name=op.f("ck_orders_ui_ref_object")
        ),
        sa.CheckConstraint(
            "ui_stage IS NULL OR ui_stage IN ('connecting', 'done')", name=op.f("ck_orders_ui_stage")
        ),
        sa.CheckConstraint("length(currency) BETWEEN 3 AND 8", name=op.f("ck_orders_currency_len")),
        sa.CheckConstraint(
            "parent_order_id IS NULL OR parent_order_id <> id", name=op.f("ck_orders_parent_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["parent_order_id"],
            ["orders.id"],
            name=op.f("fk_orders_parent_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_orders_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("public_id", name=op.f("uq_orders_public_id")),
    )
    op.create_index(
        "ix_orders_awaiting_until",
        "orders",
        ["autocomplete_until"],
        unique=False,
        postgresql_where=sa.text("status = 'awaiting_funds'"),
    )
    op.create_index(
        "ix_orders_parent",
        "orders",
        ["parent_order_id"],
        unique=False,
        postgresql_where=sa.text("parent_order_id IS NOT NULL"),
    )
    op.create_index("ix_orders_user_created", "orders", ["user_id", "created_at"], unique=False)
    op.create_index(
        "uq_orders_user_awaiting_funds",
        "orders",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'awaiting_funds'"),
    )
    op.create_table(
        "trial_grants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "user_id IS NOT NULL OR telegram_id IS NOT NULL", name=op.f("ck_trial_grants_has_owner")
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_trial_grants_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trial_grants_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trial_grants")),
        sa.UniqueConstraint("telegram_id", name="uq_trial_grants_telegram_id"),
        sa.UniqueConstraint("user_id", name="uq_trial_grants_user_id"),
    )
    op.create_table(
        "user_devices",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "devices",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(devices) = 'array'", name=op.f("ck_user_devices_devices_array")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_user_devices_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_user_devices")),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name=op.f("ck_order_items_payload_object")),
        sa.CheckConstraint(
            "status IN ('pending', 'fulfilled', 'refunded')", name=op.f("ck_order_items_status")
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_order_items_amount")),
        sa.CheckConstraint("length(type) BETWEEN 1 AND 32", name=op.f("ck_order_items_type_len")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("order_id", "position", name="uq_order_items_order_position"),
    )
    op.create_index(
        "ix_subscription_events_ref_lookup",
        "subscription_events",
        ["ref_type", "ref_id"],
        unique=False,
        postgresql_where=sa.text("ref_id IS NOT NULL"),
    )
    op.add_column(
        "subscriptions",
        sa.Column("hold_zeroed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "subscriptions", sa.Column("is_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "subscriptions", sa.Column("extra_devices", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "cooldowns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("wallet_minor", sa.BigInteger(), server_default=sa.text("0"), nullable=False)
    )
    op.create_check_constraint(op.f("ck_users_wallet_minor"), "users", "wallet_minor >= 0")
    op.drop_constraint(op.f("ck_subscriptions_disabled_reason"), "subscriptions", type_="check")
    op.create_check_constraint(op.f("ck_subscriptions_disabled_reason"), "subscriptions", _REASONS_NEW)
    for name, condition in _SUB_CHECKS:
        op.create_check_constraint(op.f(f"ck_subscriptions_{name}"), "subscriptions", condition)


def downgrade() -> None:
    for name, _condition in _SUB_CHECKS:
        op.drop_constraint(op.f(f"ck_subscriptions_{name}"), "subscriptions", type_="check")
    op.drop_constraint(op.f("ck_subscriptions_disabled_reason"), "subscriptions", type_="check")
    op.create_check_constraint(op.f("ck_subscriptions_disabled_reason"), "subscriptions", _REASONS_OLD)
    op.drop_constraint(op.f("ck_users_wallet_minor"), "users", type_="check")
    op.drop_column("users", "wallet_minor")
    op.drop_column("subscriptions", "cooldowns")
    op.drop_column("subscriptions", "extra_devices")
    op.drop_column("subscriptions", "is_trial")
    op.drop_column("subscriptions", "hold_zeroed")
    op.drop_index(
        "ix_subscription_events_ref_lookup",
        table_name="subscription_events",
        postgresql_where=sa.text("ref_id IS NOT NULL"),
    )
    op.drop_table("order_items")
    op.drop_table("user_devices")
    op.drop_table("trial_grants")
    op.drop_index(
        "uq_orders_user_awaiting_funds",
        table_name="orders",
        postgresql_where=sa.text("status = 'awaiting_funds'"),
    )
    op.drop_index("ix_orders_user_created", table_name="orders")
    op.drop_index(
        "ix_orders_parent", table_name="orders", postgresql_where=sa.text("parent_order_id IS NOT NULL")
    )
    op.drop_index(
        "ix_orders_awaiting_until", table_name="orders", postgresql_where=sa.text("status = 'awaiting_funds'")
    )
    op.drop_table("orders")
    op.drop_index("ix_notification_log_created_at", table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(
        "ix_manual_receipts_open",
        table_name="manual_receipts",
        postgresql_where=sa.text("status = 'submitted'"),
    )
    op.drop_table("manual_receipts")
    op.drop_index("ix_wallet_ledger_user_id", table_name="wallet_ledger")
    op.drop_index("ix_wallet_ledger_ref", table_name="wallet_ledger")
    op.drop_table("wallet_ledger")
    op.drop_table("plan_prices")
    op.drop_index("ix_payments_user_created", table_name="payments")
    op.drop_index(
        "ix_payments_order_id", table_name="payments", postgresql_where=sa.text("order_id IS NOT NULL")
    )
    op.drop_index(
        "ix_payments_due",
        table_name="payments",
        postgresql_where=sa.text("status = 'pending' AND next_check_at IS NOT NULL"),
    )
    op.drop_table("payments")
    op.drop_index("uq_payment_events_body", table_name="payment_events", postgresql_where=sa.text("accepted"))
    op.drop_index("ix_payment_events_received_at", table_name="payment_events")
    op.drop_index(
        "ix_payment_events_payment",
        table_name="payment_events",
        postgresql_where=sa.text("payment_id IS NOT NULL"),
    )
    op.drop_table("payment_events")
    op.drop_index("uq_plans_trial", table_name="plans", postgresql_where=sa.text("is_trial"))
    op.drop_table("plans")
    op.drop_table("payment_instances")
    op.drop_table("locations")
    op.drop_table("channel_members")
