"""Stages 3–4: promo, pages, ads, deeplinks, broadcasts, referral, LTE, IP Guard, Bedolaga importer.

Tables: ``promocodes``, ``promo_uses``, ``promo_pending`` (``svbg.promo.tables``); ``pages``,
``page_versions``, ``page_consents`` (``svbg.pages.tables``); ``ad_links``, ``ad_link_users``
(``svbg.ads.tables``); ``deeplinks``, ``deeplink_hits``, ``deeplink_daily`` (``svbg.deeplinks.tables``);
``broadcasts``, ``broadcast_msgs`` (``svbg.broadcasts.tables``); ``referral_codes``, ``referrals``,
``referral_rewards`` (``svbg.referral.tables``); the 14 ``lte_*`` tables (``svbg.ext.lte.tables``) plus
``lte_kv`` / ``lte_event_cursor`` (``svbg.ext.lte.service``); ``ip_guard_*`` (``svbg.ext.ip_guard.tables``);
``legacy_id_map``, ``legacy_transactions`` (``svbg.importers``).

Changes of existing tables: ``users.notify_marketing``; ``ck_import_runs_mode`` allows ``'shadow'``;
``ck_orders_kind`` allows ``'addon_lte'``; the admin search / dashboard indexes of
``svbg.tg.admin.users.search.INDEX_DDL`` (pg_trgm GIN on ``lower(...)``, ``users.created_at``, paid
payments).

Generated by ``alembic revision --autogenerate`` against a database at ``0003_stage2`` (PostgreSQL 17), then
reviewed by hand: the false positives on ``*.public_id`` / ``payments.id`` (same UUIDv7 default, different
text after PostgreSQL normalised it) were removed; the CHECK changes of existing tables (autogenerate does
not compare CHECKs) and the raw ``INDEX_DDL`` (frozen copy) were added. ``tests/e2e/test_migrations.py``
checks that ``upgrade head`` produces exactly the schema of ``svbg.db.schema.create_schema``.

Downgrade: drops every table and column of this revision; ``import_runs`` of mode ``'shadow'`` become
``'dry_run'`` (a shadow run never writes), and ``ck_orders_kind`` is restored ``NOT VALID`` so existing
``addon_lte`` orders do not block it while new ones are rejected.

Revision ID: 0004_stage3_4
Revises: 0003_stage2
Create Date: 2026-10-02
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_stage3_4"
down_revision: str | None = "0003_stage2"
branch_labels: str | None = None
depends_on: str | None = None

_MODES_OLD = "mode IN ('dry_run', 'apply')"
_MODES_NEW = "mode IN ('dry_run', 'apply', 'shadow')"
_KINDS_OLD = "kind IN ('new', 'renew', 'change', 'addon_devices', 'topup')"
_KINDS_NEW = "kind IN ('new', 'renew', 'change', 'addon_devices', 'addon_lte', 'topup')"

#: ``svbg.tg.admin.users.search.INDEX_DDL`` at this revision (frozen on purpose).
_INDEX_DDL: tuple[str, ...] = (
    "CREATE INDEX IF NOT EXISTS ix_users_username_trgm ON users USING gin (lower(username) gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS ix_users_first_name_trgm ON users USING gin (lower(first_name) gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS ix_subscriptions_panel_username_trgm ON subscriptions "
    "USING gin (lower(panel_username) gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS ix_subscriptions_short_uuid_trgm ON subscriptions "
    "USING gin (lower(panel_short_uuid) gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS ix_users_created_at ON users (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_payments_paid_at ON payments (paid_at) WHERE status = 'paid'",
)
_INDEX_NAMES: tuple[str, ...] = (
    "ix_users_username_trgm",
    "ix_users_first_name_trgm",
    "ix_subscriptions_panel_username_trgm",
    "ix_subscriptions_short_uuid_trgm",
    "ix_users_created_at",
    "ix_payments_paid_at",
)


def upgrade() -> None:
    op.create_table(
        "ad_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "bonus",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'{"type": "none"}\'::jsonb'),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("clicks", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.Column("legacy_id", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Za-z0-9_-]{1,64}$'", name=op.f("ck_ad_links_code_format")),
        sa.CheckConstraint("jsonb_typeof(bonus) = 'object'", name=op.f("ck_ad_links_bonus_object")),
        sa.CheckConstraint("source IN ('bot', 'import')", name=op.f("ck_ad_links_source")),
        sa.CheckConstraint("clicks >= 0", name=op.f("ck_ad_links_clicks")),
        sa.CheckConstraint("length(title) BETWEEN 1 AND 128", name=op.f("ck_ad_links_title_len")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_links")),
        sa.UniqueConstraint("code", name=op.f("uq_ad_links_code")),
    )
    op.create_index(
        "uq_ad_links_legacy",
        "ad_links",
        ["source", "legacy_id"],
        unique=True,
        postgresql_where=sa.text("legacy_id IS NOT NULL"),
    )
    op.create_table(
        "deeplink_daily",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("link_key", sa.Text(), nullable=False),
        sa.Column("link_id", sa.BigInteger(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("users", sa.Integer(), nullable=False),
        sa.Column("new_users", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "hits >= users AND users >= new_users AND new_users >= 0", name=op.f("ck_deeplink_daily_counts")
        ),
        sa.PrimaryKeyConstraint("day", "link_key", name="pk_deeplink_daily"),
    )
    op.create_index("ix_deeplink_daily_link_id_day", "deeplink_daily", ["link_id", "day"], unique=False)
    op.create_table(
        "ip_guard_nodes",
        sa.Column("node_uuid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("address", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("cdn", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(node_uuid) BETWEEN 1 AND 64", name=op.f("ck_ip_guard_nodes_uuid_len")),
        sa.PrimaryKeyConstraint("node_uuid", name=op.f("pk_ip_guard_nodes")),
    )
    op.create_table(
        "legacy_id_map",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("old_id", sa.Text(), nullable=False),
        sa.Column("new_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name=op.f("ck_legacy_id_map_data_object")),
        sa.CheckConstraint(
            "length(source) BETWEEN 1 AND 32 AND length(entity) BETWEEN 1 AND 32",
            name=op.f("ck_legacy_id_map_names"),
        ),
        sa.PrimaryKeyConstraint("source", "entity", "old_id", name="pk_legacy_id_map"),
    )
    op.create_index("ix_legacy_id_map_new", "legacy_id_map", ["source", "entity", "new_id"], unique=False)
    op.create_table(
        "legacy_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("legacy_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("payment_method", sa.Text(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("pair_key", sa.Text(), nullable=True),
        sa.Column("counts_as_revenue", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "length(currency) BETWEEN 3 AND 8", name=op.f("ck_legacy_transactions_currency_len")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_transactions")),
        sa.UniqueConstraint("source", "legacy_id", name="uq_legacy_transactions_source_legacy_id"),
    )
    op.create_index(
        "ix_legacy_transactions_external",
        "legacy_transactions",
        ["external_id"],
        unique=False,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_index(
        "ix_legacy_transactions_user", "legacy_transactions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "lte_counters",
        sa.Column("node_uuid", sa.Text(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("panel_user_id", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("accounted", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("baseline", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("carry", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("vanished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "baseline + accounted = total + carry", name=op.f("ck_lte_counters_key_invariant")
        ),
        sa.CheckConstraint(
            "total >= 0 AND accounted >= 0 AND baseline >= 0 AND carry >= 0",
            name=op.f("ck_lte_counters_non_negative"),
        ),
        sa.PrimaryKeyConstraint("node_uuid", "usage_date", "panel_user_id", name="pk_lte_counters"),
    )
    op.create_index("ix_lte_counters_usage_date", "lte_counters", ["usage_date"], unique=False)
    op.create_table(
        "lte_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "name",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("state", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("enforce", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("margin_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("margin_pct", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("limit_default_bytes", sa.BigInteger(), nullable=True),
        sa.Column("has_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("limit_trial_bytes", sa.BigInteger(), nullable=True),
        sa.Column("has_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("squad_uuid", sa.Text(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(name) = 'object'", name=op.f("ck_lte_groups_name_object")),
        sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9_-]{0,31}$'", name=op.f("ck_lte_groups_slug_format")),
        sa.CheckConstraint("state <> 'active' OR has_default", name=op.f("ck_lte_groups_active_has_default")),
        sa.CheckConstraint("state IN ('draft', 'active', 'suspended')", name=op.f("ck_lte_groups_state")),
        sa.CheckConstraint(
            "has_default OR limit_default_bytes IS NULL", name=op.f("ck_lte_groups_default_value_needs_flag")
        ),
        sa.CheckConstraint(
            "has_trial OR limit_trial_bytes IS NULL", name=op.f("ck_lte_groups_trial_value_needs_flag")
        ),
        sa.CheckConstraint(
            "limit_default_bytes IS NULL OR limit_default_bytes >= 0",
            name=op.f("ck_lte_groups_limit_default"),
        ),
        sa.CheckConstraint(
            "limit_trial_bytes IS NULL OR limit_trial_bytes >= 0", name=op.f("ck_lte_groups_limit_trial")
        ),
        sa.CheckConstraint("margin_bytes >= 0", name=op.f("ck_lte_groups_margin_bytes")),
        sa.CheckConstraint("margin_pct BETWEEN 0 AND 100", name=op.f("ck_lte_groups_margin_pct")),
        sa.CheckConstraint("version > 0", name=op.f("ck_lte_groups_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lte_groups")),
        sa.UniqueConstraint("slug", name=op.f("uq_lte_groups_slug")),
    )
    op.create_table(
        "lte_kv",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(key) BETWEEN 1 AND 64", name=op.f("ck_lte_kv_key_len")),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_lte_kv")),
    )
    op.create_table(
        "lte_node_state",
        sa.Column("node_uuid", sa.Text(), nullable=False),
        sa.Column("first_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ok_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ok_read_date", sa.Date(), nullable=True),
        sa.Column("gap_anchor_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gap_tail", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("disconnected_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("xray_uptime_s", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("gap_tail >= 0", name=op.f("ck_lte_node_state_gap_tail")),
        sa.PrimaryKeyConstraint("node_uuid", name=op.f("pk_lte_node_state")),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), server_default=sa.text("'custom'"), nullable=False),
        sa.Column(
            "title",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "body",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("consent_version", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("code ~ '^[a-z][a-z0-9_]{0,23}$'", name=op.f("ck_pages_code_format")),
        sa.CheckConstraint("jsonb_typeof(body) = 'object'", name=op.f("ck_pages_body_object")),
        sa.CheckConstraint("jsonb_typeof(title) = 'object'", name=op.f("ck_pages_title_object")),
        sa.CheckConstraint(
            "kind IN ('faq', 'rules', 'offer', 'consent', 'custom')", name=op.f("ck_pages_kind")
        ),
        sa.CheckConstraint(
            "consent_version IS NULL OR consent_version BETWEEN 1 AND version",
            name=op.f("ck_pages_consent_version"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_pages_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("code", name=op.f("uq_pages_code")),
    )
    op.create_table(
        "promocodes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("percent", sa.SmallInteger(), nullable=True),
        sa.Column("plan_id", sa.BigInteger(), nullable=True),
        sa.Column("pending_hours", sa.Integer(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("uses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("once_per_user", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("new_users_only", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("min_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column(
            "plan_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.Column("legacy_id", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(plan_ids) = 'array'", name=op.f("ck_promocodes_plan_ids_array")),
        sa.CheckConstraint(
            "kind IN ('days', 'percent', 'fixed', 'wallet', 'trial_extend', 'plan_gift', 'wallet_days')",
            name=op.f("ck_promocodes_kind"),
        ),
        sa.CheckConstraint("source IN ('bot', 'import')", name=op.f("ck_promocodes_source")),
        sa.CheckConstraint("amount_minor IS NULL OR amount_minor > 0", name=op.f("ck_promocodes_amount")),
        sa.CheckConstraint("days IS NULL OR days BETWEEN 1 AND 3650", name=op.f("ck_promocodes_days")),
        sa.CheckConstraint("length(code) BETWEEN 1 AND 64", name=op.f("ck_promocodes_code_len")),
        sa.CheckConstraint("max_uses IS NULL OR max_uses > 0", name=op.f("ck_promocodes_max_uses")),
        sa.CheckConstraint(
            "min_amount_minor IS NULL OR min_amount_minor > 0", name=op.f("ck_promocodes_min_amount")
        ),
        sa.CheckConstraint(
            "pending_hours IS NULL OR pending_hours BETWEEN 1 AND 87600",
            name=op.f("ck_promocodes_pending_hours"),
        ),
        sa.CheckConstraint(
            "percent IS NULL OR percent BETWEEN 1 AND 100", name=op.f("ck_promocodes_percent")
        ),
        sa.CheckConstraint("uses >= 0", name=op.f("ck_promocodes_uses")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promocodes")),
    )
    op.create_index("uq_promocodes_code_lower", "promocodes", [sa.literal_column("lower(code)")], unique=True)
    op.create_index(
        "uq_promocodes_legacy",
        "promocodes",
        ["source", "legacy_id"],
        unique=True,
        postgresql_where=sa.text("legacy_id IS NOT NULL"),
    )
    op.create_table(
        "ad_link_users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("ad_link_id", sa.BigInteger(), nullable=False),
        sa.Column("attached_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.CheckConstraint("source IN ('bot', 'import')", name=op.f("ck_ad_link_users_source")),
        sa.ForeignKeyConstraint(
            ["ad_link_id"],
            ["ad_links.id"],
            name=op.f("fk_ad_link_users_ad_link_id_ad_links"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ad_link_users_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_ad_link_users")),
    )
    op.create_index("ix_ad_link_users_link", "ad_link_users", ["ad_link_id", "attached_at"], unique=False)
    op.create_table(
        "broadcasts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("source_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("source_msg_id", sa.BigInteger(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "buttons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "segment",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'{"preset": "all"}\'::jsonb'),
            nullable=False,
        ),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("cursor", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "skip",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sent", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("blocked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("progress_msg", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("jsonb_typeof(buttons) = 'array'", name=op.f("ck_broadcasts_buttons_array")),
        sa.CheckConstraint("jsonb_typeof(content) = 'object'", name=op.f("ck_broadcasts_content_object")),
        sa.CheckConstraint("jsonb_typeof(options) = 'object'", name=op.f("ck_broadcasts_options_object")),
        sa.CheckConstraint("jsonb_typeof(segment) = 'object'", name=op.f("ck_broadcasts_segment_object")),
        sa.CheckConstraint("jsonb_typeof(skip) = 'array'", name=op.f("ck_broadcasts_skip_array")),
        sa.CheckConstraint(
            "status IN ('draft', 'running', 'paused', 'done', 'canceled')", name=op.f("ck_broadcasts_status")
        ),
        sa.CheckConstraint(
            "cursor >= 0 AND total >= 0 AND sent >= 0 AND failed >= 0 AND blocked >= 0",
            name=op.f("ck_broadcasts_counters"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_broadcasts_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcasts")),
    )
    op.create_index("ix_broadcasts_created_at", "broadcasts", ["created_at"], unique=False)
    op.create_index(
        "ix_broadcasts_live",
        "broadcasts",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status IN ('running', 'paused')"),
    )
    op.create_table(
        "deeplinks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("intent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("promo_id", sa.BigInteger(), nullable=True),
        sa.Column("ad_link_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("uses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Za-z0-9_-]{1,62}$'", name=op.f("ck_deeplinks_code_format")),
        sa.CheckConstraint("jsonb_typeof(intent) = 'object'", name=op.f("ck_deeplinks_intent_object")),
        sa.CheckConstraint("length(btrim(title)) BETWEEN 1 AND 64", name=op.f("ck_deeplinks_title_len")),
        sa.CheckConstraint("max_uses IS NULL OR max_uses > 0", name=op.f("ck_deeplinks_max_uses_positive")),
        sa.CheckConstraint("uses >= 0", name=op.f("ck_deeplinks_uses_non_negative")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_deeplinks_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deeplinks")),
        sa.UniqueConstraint("code", name=op.f("uq_deeplinks_code")),
    )
    op.create_index("ix_deeplinks_created_at", "deeplinks", ["created_at"], unique=False)
    op.create_table(
        "lte_group_nodes",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("node_uuid", sa.Text(), nullable=False),
        sa.Column("counted_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("counted_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "counted_to IS NULL OR counted_to >= counted_from", name=op.f("ck_lte_group_nodes_span")
        ),
        sa.CheckConstraint("node_uuid = lower(node_uuid)", name=op.f("ck_lte_group_nodes_node_uuid_lower")),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_group_nodes_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "node_uuid", "counted_from", name="pk_lte_group_nodes"),
    )
    op.create_index("ix_lte_group_nodes_node_uuid", "lte_group_nodes", ["node_uuid"], unique=False)
    op.create_table(
        "lte_packs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("gb", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), server_default=sa.text("'RUB'"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_lte_packs_currency")),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_lte_packs_amount_minor")),
        sa.CheckConstraint("gb > 0 AND gb <= 100000", name=op.f("ck_lte_packs_gb")),
        sa.ForeignKeyConstraint(
            ["group_id"], ["lte_groups.id"], name=op.f("fk_lte_packs_group_id_lte_groups"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lte_packs")),
    )
    op.create_table(
        "lte_twins",
        sa.Column("base_squad_uuid", sa.Text(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("twin_squad_uuid", sa.Text(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.CheckConstraint("base_squad_uuid <> twin_squad_uuid", name=op.f("ck_lte_twins_not_identity")),
        sa.ForeignKeyConstraint(
            ["group_id"], ["lte_groups.id"], name=op.f("fk_lte_twins_group_id_lte_groups"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("base_squad_uuid", name=op.f("pk_lte_twins")),
    )
    op.create_index("ix_lte_twins_group_id", "lte_twins", ["group_id"], unique=False)
    op.create_table(
        "page_consents",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], name=op.f("fk_page_consents_page_id_pages"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_page_consents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "page_id", name="pk_page_consents"),
    )
    op.create_table(
        "page_versions",
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], name=op.f("fk_page_versions_page_id_pages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("page_id", "version", name="pk_page_versions"),
    )
    op.create_table(
        "promo_pending",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("promo_id", sa.BigInteger(), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "source IN ('bot', 'link', 'admin', 'import')", name=op.f("ck_promo_pending_source")
        ),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promocodes.id"],
            name=op.f("fk_promo_pending_promo_id_promocodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_promo_pending_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_promo_pending")),
    )
    op.create_index("ix_promo_pending_until", "promo_pending", ["until"], unique=False)
    op.create_table(
        "promo_uses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("promo_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.Column(
            "effect",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "source IN ('bot', 'link', 'checkout', 'admin', 'import', 'site')",
            name=op.f("ck_promo_uses_source"),
        ),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promocodes.id"],
            name=op.f("fk_promo_uses_promo_id_promocodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_promo_uses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_uses")),
    )
    op.create_index("ix_promo_uses_promo_user", "promo_uses", ["promo_id", "user_id"], unique=False)
    op.create_index("ix_promo_uses_user", "promo_uses", ["user_id"], unique=False)
    op.create_index(
        "uq_promo_uses_order",
        "promo_uses",
        ["promo_id", "order_id"],
        unique=True,
        postgresql_where=sa.text("order_id IS NOT NULL"),
    )
    op.create_table(
        "referral_codes",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'bot'"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Za-z0-9_-]{1,62}$'", name=op.f("ck_referral_codes_code_format")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_referral_codes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_referral_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_referral_codes_code")),
    )
    op.create_table(
        "referrals",
        sa.Column("referred_user_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("attached_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'link'"), nullable=False),
        sa.CheckConstraint("referred_user_id <> referrer_id", name=op.f("ck_referrals_not_self")),
        sa.ForeignKeyConstraint(
            ["referred_user_id"],
            ["users.id"],
            name=op.f("fk_referrals_referred_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"], ["users.id"], name=op.f("fk_referrals_referrer_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("referred_user_id", name=op.f("pk_referrals")),
    )
    op.create_index("ix_referrals_attached_at", "referrals", ["attached_at"], unique=False)
    op.create_index("ix_referrals_referrer_id", "referrals", ["referrer_id"], unique=False)
    op.create_table(
        "broadcast_msgs",
        sa.Column("broadcast_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("msg_id", sa.BigInteger(), nullable=False),
        sa.Column("delete_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_broadcast_msgs_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("broadcast_id", "user_id", name="pk_broadcast_msgs"),
    )
    op.create_index("ix_broadcast_msgs_due", "broadcast_msgs", ["broadcast_id", "delete_at"], unique=False)
    op.create_table(
        "deeplink_hits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("link_id", sa.BigInteger(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_new", sa.Boolean(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('screen', 'plan', 'promo', 'topup', 'ref', 'ad', 'link', 'legacy_ref', 'ad_code')",
            name=op.f("ck_deeplink_hits_kind"),
        ),
        sa.CheckConstraint("length(payload) BETWEEN 1 AND 64", name=op.f("ck_deeplink_hits_payload_len")),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["deeplinks.id"],
            name=op.f("fk_deeplink_hits_link_id_deeplinks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_deeplink_hits_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deeplink_hits")),
    )
    op.create_index("ix_deeplink_hits_link_id_ts", "deeplink_hits", ["link_id", "ts"], unique=False)
    op.create_index("ix_deeplink_hits_link_id_user_id", "deeplink_hits", ["link_id", "user_id"], unique=False)
    op.create_index("ix_deeplink_hits_ts", "deeplink_hits", ["ts"], unique=False)
    op.create_index("ix_deeplink_hits_user_id", "deeplink_hits", ["user_id"], unique=False)
    op.create_table(
        "ip_guard_alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column("panel_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("card_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("card_msg_id", sa.BigInteger(), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("acked_by", sa.BigInteger(), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quarantine_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "members",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(evidence) = 'object'", name=op.f("ck_ip_guard_alerts_evidence_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(members) = 'object'", name=op.f("ck_ip_guard_alerts_members_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(metrics) = 'object'", name=op.f("ck_ip_guard_alerts_metrics_object")
        ),
        sa.CheckConstraint(
            "kind <> 'not_blocked' OR reason IN "
            "('pool', 'unconfirmed', 'incomplete', 'grace', 'whitelist', 'dismissed', 'precondition')",
            name=op.f("ck_ip_guard_alerts_not_blocked_reason"),
        ),
        sa.CheckConstraint(
            "kind IN ('warn', 'not_blocked', 'block_failed', 'anomaly', 'digest')",
            name=op.f("ck_ip_guard_alerts_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_ip_guard_alerts_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ip_guard_alerts")),
    )
    op.create_index("ix_ip_guard_alerts_kind", "ip_guard_alerts", ["kind", "created_at"], unique=False)
    op.create_index(
        "ix_ip_guard_alerts_quarantine",
        "ip_guard_alerts",
        ["quarantine_until"],
        unique=False,
        postgresql_where=sa.text("kind = 'anomaly'"),
    )
    op.create_index(
        "ix_ip_guard_alerts_sub", "ip_guard_alerts", ["subscription_id", "created_at"], unique=False
    )
    op.create_table(
        "ip_guard_blocks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("panel_user_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("blocked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("blocked_by", sa.BigInteger(), nullable=True),
        sa.Column("ip_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("live_ip_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("subnet_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("frozen_seconds", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("zeroed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("card_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("card_msg_id", sa.BigInteger(), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("confirmed_by", sa.BigInteger(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unblock_mode", sa.Text(), nullable=True),
        sa.Column("unblocked_by", sa.BigInteger(), nullable=True),
        sa.Column("unblocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("new_paid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.BigInteger(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "events",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("evidence_purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("jsonb_typeof(events) = 'array'", name=op.f("ck_ip_guard_blocks_events_array")),
        sa.CheckConstraint(
            "jsonb_typeof(evidence) = 'object'", name=op.f("ck_ip_guard_blocks_evidence_object")
        ),
        sa.CheckConstraint("reason IN ('auto', 'manual', 'anomaly')", name=op.f("ck_ip_guard_blocks_reason")),
        sa.CheckConstraint(
            "status IN ('active', 'unblocked', 'closed')", name=op.f("ck_ip_guard_blocks_status")
        ),
        sa.CheckConstraint(
            "unblock_mode IS NULL OR unblock_mode IN ('plain', 'revoke')",
            name=op.f("ck_ip_guard_blocks_unblock_mode"),
        ),
        sa.CheckConstraint("frozen_seconds >= 0", name=op.f("ck_ip_guard_blocks_frozen_seconds")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_ip_guard_blocks_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ip_guard_blocks_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ip_guard_blocks")),
    )
    op.create_index(
        "ix_ip_guard_blocks_panel_user",
        "ip_guard_blocks",
        ["panel_user_id"],
        unique=False,
        postgresql_where=sa.text("panel_user_id IS NOT NULL"),
    )
    op.create_index(
        "ix_ip_guard_blocks_purge",
        "ip_guard_blocks",
        ["evidence_purge_at"],
        unique=False,
        postgresql_where=sa.text("evidence_purge_at IS NOT NULL"),
    )
    op.create_index("ix_ip_guard_blocks_status", "ip_guard_blocks", ["status", "blocked_at"], unique=False)
    op.create_index(
        "ix_ip_guard_blocks_sub", "ip_guard_blocks", ["subscription_id", "blocked_at"], unique=False
    )
    op.create_index(
        "uq_ip_guard_blocks_active",
        "ip_guard_blocks",
        ["subscription_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "ip_guard_exempt",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(btrim(reason)) > 0", name=op.f("ck_ip_guard_exempt_reason_not_empty")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_ip_guard_exempt_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_ip_guard_exempt")),
    )
    op.create_table(
        "lte_anchors",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("anchor_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("anchor_kind", sa.Text(), nullable=False),
        sa.Column("anchor_source", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("series_open", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("series_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("series_closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coverage_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "anchor_kind IN ('paid', 'admin', 'trial', 'provisional', 'manual', 'import')",
            name=op.f("ck_lte_anchors_anchor_kind"),
        ),
        sa.CheckConstraint(
            "series_open OR series_closed_at IS NOT NULL", name=op.f("ck_lte_anchors_closed_has_time")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_lte_anchors_version_positive")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_anchors_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_lte_anchors")),
    )
    op.create_index(
        "ix_lte_anchors_review",
        "lte_anchors",
        ["subscription_id"],
        unique=False,
        postgresql_where=sa.text("review_reason IS NOT NULL"),
    )
    op.create_table(
        "lte_event_cursor",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("last_event_id", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("last_event_id >= 0", name=op.f("ck_lte_event_cursor_last_event_id")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_event_cursor_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_lte_event_cursor")),
    )
    op.create_table(
        "lte_periods",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("anchor_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_cause", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("is_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("start_estimated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "(state = 'closed') = (ended_at IS NOT NULL)", name=op.f("ck_lte_periods_closed_has_end")
        ),
        sa.CheckConstraint("state IN ('open', 'deferred', 'closed')", name=op.f("ck_lte_periods_state")),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= starts_at", name=op.f("ck_lte_periods_end_after_start")
        ),
        sa.CheckConstraint("idx >= 0", name=op.f("ck_lte_periods_idx")),
        sa.CheckConstraint("planned_end_at > starts_at", name=op.f("ck_lte_periods_planned_after_start")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_periods_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lte_periods")),
    )
    op.create_index(
        "ix_lte_periods_closed_end",
        "lte_periods",
        ["ended_at"],
        unique=False,
        postgresql_where=sa.text("state = 'closed'"),
    )
    op.create_index(
        "ix_lte_periods_open_end",
        "lte_periods",
        ["planned_end_at"],
        unique=False,
        postgresql_where=sa.text("state = 'open'"),
    )
    op.create_index(
        "ix_lte_periods_sub_starts", "lte_periods", ["subscription_id", "starts_at"], unique=False
    )
    op.create_index(
        "uq_lte_periods_live",
        "lte_periods",
        ["subscription_id"],
        unique=True,
        postgresql_where=sa.text("state <> 'closed'"),
    )
    op.create_table(
        "lte_usage_daily",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("msk_date", sa.Date(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("after_block_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "bytes >= 0 AND after_block_bytes >= 0", name=op.f("ck_lte_usage_daily_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_usage_daily_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_usage_daily_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", "group_id", "msk_date", name="pk_lte_usage_daily"),
    )
    op.create_index("ix_lte_usage_daily_msk_date", "lte_usage_daily", ["msk_date"], unique=False)
    op.create_table(
        "lte_usage_hourly",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("hour_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("bytes >= 0", name=op.f("ck_lte_usage_hourly_bytes")),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_usage_hourly_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_usage_hourly_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", "group_id", "hour_utc", name="pk_lte_usage_hourly"),
    )
    op.create_index("ix_lte_usage_hourly_hour_utc", "lte_usage_hourly", ["hour_utc"], unique=False)
    op.create_table(
        "referral_rewards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("referred_user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("payment_id", sa.Text(), nullable=True),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind <> 'wallet_pct' OR payment_id IS NOT NULL", name=op.f("ck_referral_rewards_pct_has_payment")
        ),
        sa.CheckConstraint("kind IN ('days', 'wallet_pct')", name=op.f("ck_referral_rewards_kind")),
        sa.CheckConstraint("side IN ('inviter', 'invitee')", name=op.f("ck_referral_rewards_side")),
        sa.CheckConstraint(
            "status <> 'deferred' OR retry_until IS NOT NULL",
            name=op.f("ck_referral_rewards_deferred_has_retry"),
        ),
        sa.CheckConstraint(
            "status <> 'granted' OR granted_at IS NOT NULL", name=op.f("ck_referral_rewards_granted_has_time")
        ),
        sa.CheckConstraint(
            "status IN ('granted', 'deferred', 'expired', 'denied', 'legacy')",
            name=op.f("ck_referral_rewards_status"),
        ),
        sa.CheckConstraint(
            "amount_minor IS NULL OR amount_minor > 0", name=op.f("ck_referral_rewards_amount_positive")
        ),
        sa.CheckConstraint("days IS NULL OR days > 0", name=op.f("ck_referral_rewards_days_positive")),
        sa.ForeignKeyConstraint(
            ["referred_user_id"],
            ["referrals.referred_user_id"],
            name=op.f("fk_referral_rewards_referred_user_id_referrals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_referral_rewards_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_referral_rewards_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_rewards")),
    )
    op.create_index(
        "ix_referral_rewards_deferred",
        "referral_rewards",
        ["retry_until"],
        unique=False,
        postgresql_where=sa.text("status = 'deferred'"),
    )
    op.create_index(
        "ix_referral_rewards_user", "referral_rewards", ["user_id", "kind", "side", "status"], unique=False
    )
    op.create_index(
        "uq_referral_rewards_days_side",
        "referral_rewards",
        ["referred_user_id", "side"],
        unique=True,
        postgresql_where=sa.text("kind = 'days'"),
    )
    op.create_index(
        "uq_referral_rewards_pct_payment_side",
        "referral_rewards",
        ["payment_id", "side"],
        unique=True,
        postgresql_where=sa.text("kind = 'wallet_pct'"),
    )
    op.create_table(
        "lte_blocks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("period_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), server_default=sa.text("'enforce'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("used_at_block", sa.BigInteger(), nullable=True),
        sa.Column("limit_at_block", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resend_done_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status IN ('released', 'cancelled')) = (released_at IS NOT NULL)",
            name=op.f("ck_lte_blocks_released_has_time"),
        ),
        sa.CheckConstraint("mode IN ('enforce', 'shadow')", name=op.f("ck_lte_blocks_mode")),
        sa.CheckConstraint("reason IN ('quota', 'unavailable', 'manual')", name=op.f("ck_lte_blocks_reason")),
        sa.CheckConstraint(
            "status = 'active' OR release_reason IS NOT NULL", name=op.f("ck_lte_blocks_release_has_reason")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'releasing', 'released', 'cancelled')", name=op.f("ck_lte_blocks_status")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_blocks_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["lte_periods.id"],
            name=op.f("fk_lte_blocks_period_id_lte_periods"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_blocks_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lte_blocks")),
    )
    op.create_index(
        "ix_lte_blocks_live_group",
        "lte_blocks",
        ["group_id"],
        unique=False,
        postgresql_where=sa.text("status IN ('active', 'releasing')"),
    )
    op.create_index(
        "uq_lte_blocks_live",
        "lte_blocks",
        ["subscription_id", "group_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('active', 'releasing')"),
    )
    op.create_table(
        "lte_credits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("period_id", sa.BigInteger(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("source IN ('order', 'admin', 'import')", name=op.f("ck_lte_credits_source")),
        sa.CheckConstraint(
            "status = 'active' OR expired_at IS NOT NULL", name=op.f("ck_lte_credits_inactive_has_time")
        ),
        sa.CheckConstraint("status IN ('active', 'expired', 'refunded')", name=op.f("ck_lte_credits_status")),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_lte_credits_amount_minor")),
        sa.CheckConstraint("bytes > 0", name=op.f("ck_lte_credits_bytes_positive")),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_credits_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_lte_credits_order_id_orders"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["lte_periods.id"],
            name=op.f("fk_lte_credits_period_id_lte_periods"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_credits_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lte_credits")),
        sa.UniqueConstraint("order_id", name=op.f("uq_lte_credits_order_id")),
    )
    op.create_index(
        "ix_lte_credits_period_active",
        "lte_credits",
        ["period_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "lte_overrides",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column("applies_to", sa.Text(), server_default=sa.text("'all'"), nullable=False),
        sa.Column("period_id", sa.BigInteger(), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exempt_kind", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'exempt') = (exempt_kind IS NOT NULL)", name=op.f("ck_lte_overrides_exempt_has_kind")
        ),
        sa.CheckConstraint(
            "applies_to IN ('all', 'paid', 'trial')", name=op.f("ck_lte_overrides_applies_to")
        ),
        sa.CheckConstraint(
            "exempt_kind IS NULL OR exempt_kind IN ('owner', 'launch_trial', 'manual')",
            name=op.f("ck_lte_overrides_exempt_kind"),
        ),
        sa.CheckConstraint(
            "kind = 'limit' OR limit_bytes IS NULL", name=op.f("ck_lte_overrides_limit_only_for_limit")
        ),
        sa.CheckConstraint("kind IN ('limit', 'exempt', 'no_block')", name=op.f("ck_lte_overrides_kind")),
        sa.CheckConstraint(
            "limit_bytes IS NULL OR limit_bytes >= 0", name=op.f("ck_lte_overrides_limit_bytes")
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoke_reason IS NOT NULL",
            name=op.f("ck_lte_overrides_revoked_has_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_overrides_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["lte_periods.id"],
            name=op.f("fk_lte_overrides_period_id_lte_periods"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_lte_overrides_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lte_overrides")),
    )
    op.create_index(
        "ix_lte_overrides_live",
        "lte_overrides",
        ["subscription_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "uq_lte_overrides_live_exempt",
        "lte_overrides",
        ["subscription_id", sa.literal_column("coalesce(group_id, 0)")],
        unique=True,
        postgresql_where=sa.text("kind = 'exempt' AND revoked_at IS NULL"),
    )
    op.create_table(
        "lte_period_usage",
        sa.Column("period_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("after_block_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("estimated_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_delta_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "used_bytes >= 0 AND after_block_bytes >= 0 AND estimated_bytes >= 0",
            name=op.f("ck_lte_period_usage_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["lte_groups.id"],
            name=op.f("fk_lte_period_usage_group_id_lte_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["lte_periods.id"],
            name=op.f("fk_lte_period_usage_period_id_lte_periods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("period_id", "group_id", name="pk_lte_period_usage"),
    )
    op.add_column(
        "users", sa.Column("notify_marketing", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    op.drop_constraint(op.f("ck_import_runs_mode"), "import_runs", type_="check")
    op.create_check_constraint(op.f("ck_import_runs_mode"), "import_runs", _MODES_NEW)
    op.drop_constraint(op.f("ck_orders_kind"), "orders", type_="check")
    op.create_check_constraint(op.f("ck_orders_kind"), "orders", _KINDS_NEW)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for ddl in _INDEX_DDL:
        op.execute(ddl)


def downgrade() -> None:
    for name in reversed(_INDEX_NAMES):
        op.execute(f"DROP INDEX IF EXISTS {name}")
    op.drop_constraint(op.f("ck_orders_kind"), "orders", type_="check")
    op.execute(f"ALTER TABLE orders ADD CONSTRAINT ck_orders_kind CHECK ({_KINDS_OLD}) NOT VALID")
    op.drop_constraint(op.f("ck_import_runs_mode"), "import_runs", type_="check")
    op.execute("UPDATE import_runs SET mode = 'dry_run' WHERE mode = 'shadow'")
    op.create_check_constraint(op.f("ck_import_runs_mode"), "import_runs", _MODES_OLD)
    op.drop_column("users", "notify_marketing")
    op.drop_table("lte_period_usage")
    op.drop_index(
        "uq_lte_overrides_live_exempt",
        table_name="lte_overrides",
        postgresql_where=sa.text("kind = 'exempt' AND revoked_at IS NULL"),
    )
    op.drop_index(
        "ix_lte_overrides_live", table_name="lte_overrides", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_table("lte_overrides")
    op.drop_index(
        "ix_lte_credits_period_active",
        table_name="lte_credits",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("lte_credits")
    op.drop_index(
        "uq_lte_blocks_live",
        table_name="lte_blocks",
        postgresql_where=sa.text("status IN ('active', 'releasing')"),
    )
    op.drop_index(
        "ix_lte_blocks_live_group",
        table_name="lte_blocks",
        postgresql_where=sa.text("status IN ('active', 'releasing')"),
    )
    op.drop_table("lte_blocks")
    op.drop_index(
        "uq_referral_rewards_pct_payment_side",
        table_name="referral_rewards",
        postgresql_where=sa.text("kind = 'wallet_pct'"),
    )
    op.drop_index(
        "uq_referral_rewards_days_side",
        table_name="referral_rewards",
        postgresql_where=sa.text("kind = 'days'"),
    )
    op.drop_index("ix_referral_rewards_user", table_name="referral_rewards")
    op.drop_index(
        "ix_referral_rewards_deferred",
        table_name="referral_rewards",
        postgresql_where=sa.text("status = 'deferred'"),
    )
    op.drop_table("referral_rewards")
    op.drop_index("ix_lte_usage_hourly_hour_utc", table_name="lte_usage_hourly")
    op.drop_table("lte_usage_hourly")
    op.drop_index("ix_lte_usage_daily_msk_date", table_name="lte_usage_daily")
    op.drop_table("lte_usage_daily")
    op.drop_index(
        "uq_lte_periods_live", table_name="lte_periods", postgresql_where=sa.text("state <> 'closed'")
    )
    op.drop_index("ix_lte_periods_sub_starts", table_name="lte_periods")
    op.drop_index(
        "ix_lte_periods_open_end", table_name="lte_periods", postgresql_where=sa.text("state = 'open'")
    )
    op.drop_index(
        "ix_lte_periods_closed_end", table_name="lte_periods", postgresql_where=sa.text("state = 'closed'")
    )
    op.drop_table("lte_periods")
    op.drop_table("lte_event_cursor")
    op.drop_index(
        "ix_lte_anchors_review",
        table_name="lte_anchors",
        postgresql_where=sa.text("review_reason IS NOT NULL"),
    )
    op.drop_table("lte_anchors")
    op.drop_table("ip_guard_exempt")
    op.drop_index(
        "uq_ip_guard_blocks_active",
        table_name="ip_guard_blocks",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_ip_guard_blocks_sub", table_name="ip_guard_blocks")
    op.drop_index("ix_ip_guard_blocks_status", table_name="ip_guard_blocks")
    op.drop_index(
        "ix_ip_guard_blocks_purge",
        table_name="ip_guard_blocks",
        postgresql_where=sa.text("evidence_purge_at IS NOT NULL"),
    )
    op.drop_index(
        "ix_ip_guard_blocks_panel_user",
        table_name="ip_guard_blocks",
        postgresql_where=sa.text("panel_user_id IS NOT NULL"),
    )
    op.drop_table("ip_guard_blocks")
    op.drop_index("ix_ip_guard_alerts_sub", table_name="ip_guard_alerts")
    op.drop_index(
        "ix_ip_guard_alerts_quarantine",
        table_name="ip_guard_alerts",
        postgresql_where=sa.text("kind = 'anomaly'"),
    )
    op.drop_index("ix_ip_guard_alerts_kind", table_name="ip_guard_alerts")
    op.drop_table("ip_guard_alerts")
    op.drop_index("ix_deeplink_hits_user_id", table_name="deeplink_hits")
    op.drop_index("ix_deeplink_hits_ts", table_name="deeplink_hits")
    op.drop_index("ix_deeplink_hits_link_id_user_id", table_name="deeplink_hits")
    op.drop_index("ix_deeplink_hits_link_id_ts", table_name="deeplink_hits")
    op.drop_table("deeplink_hits")
    op.drop_index("ix_broadcast_msgs_due", table_name="broadcast_msgs")
    op.drop_table("broadcast_msgs")
    op.drop_index("ix_referrals_referrer_id", table_name="referrals")
    op.drop_index("ix_referrals_attached_at", table_name="referrals")
    op.drop_table("referrals")
    op.drop_table("referral_codes")
    op.drop_index(
        "uq_promo_uses_order", table_name="promo_uses", postgresql_where=sa.text("order_id IS NOT NULL")
    )
    op.drop_index("ix_promo_uses_user", table_name="promo_uses")
    op.drop_index("ix_promo_uses_promo_user", table_name="promo_uses")
    op.drop_table("promo_uses")
    op.drop_index("ix_promo_pending_until", table_name="promo_pending")
    op.drop_table("promo_pending")
    op.drop_table("page_versions")
    op.drop_table("page_consents")
    op.drop_index("ix_lte_twins_group_id", table_name="lte_twins")
    op.drop_table("lte_twins")
    op.drop_table("lte_packs")
    op.drop_index("ix_lte_group_nodes_node_uuid", table_name="lte_group_nodes")
    op.drop_table("lte_group_nodes")
    op.drop_index("ix_deeplinks_created_at", table_name="deeplinks")
    op.drop_table("deeplinks")
    op.drop_index(
        "ix_broadcasts_live",
        table_name="broadcasts",
        postgresql_where=sa.text("status IN ('running', 'paused')"),
    )
    op.drop_index("ix_broadcasts_created_at", table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index("ix_ad_link_users_link", table_name="ad_link_users")
    op.drop_table("ad_link_users")
    op.drop_index(
        "uq_promocodes_legacy", table_name="promocodes", postgresql_where=sa.text("legacy_id IS NOT NULL")
    )
    op.drop_index("uq_promocodes_code_lower", table_name="promocodes")
    op.drop_table("promocodes")
    op.drop_table("pages")
    op.drop_table("lte_node_state")
    op.drop_table("lte_kv")
    op.drop_table("lte_groups")
    op.drop_index("ix_lte_counters_usage_date", table_name="lte_counters")
    op.drop_table("lte_counters")
    op.drop_index("ix_legacy_transactions_user", table_name="legacy_transactions")
    op.drop_index(
        "ix_legacy_transactions_external",
        table_name="legacy_transactions",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_table("legacy_transactions")
    op.drop_index("ix_legacy_id_map_new", table_name="legacy_id_map")
    op.drop_table("legacy_id_map")
    op.drop_table("ip_guard_nodes")
    op.drop_index("ix_deeplink_daily_link_id_day", table_name="deeplink_daily")
    op.drop_table("deeplink_daily")
    op.drop_index(
        "uq_ad_links_legacy", table_name="ad_links", postgresql_where=sa.text("legacy_id IS NOT NULL")
    )
    op.drop_table("ad_links")
